### ISSUE TITLE
How edit links embed when sent in discord and other places?

### ISSUE THREAD

**Issue by carlybotofficial** [TrustedMercury/discord-bot-website-template#3]
How do I change the embed for the link when it's sent in something such as discord currently it is "An opensource discord bot website template that you can use to make your bot seem more professional!" but I cannot seem to find out how to change it, any help?

**Comment by cheeziess** [comment]
change description content at line  [16](https://github.com/TrustedMercury/discord-bot-website-template/blob/master/index.html#L16)

**Comment by kevinjosethomas** [comment]
Thanks for helping @Cheeziess <3
