### ISSUE TITLE
Can u upload commands.html too

### ISSUE THREAD

**Issue by Ishika549** [TrustedMercury/discord-bot-website-template#4]
How can I add commands is commands section bcoz as now it blanks when we use that. Sorry if the question is Silly... I m Noob in CSS and HTML...

**Comment by filipporomani** [comment]
Yes @trustedmercury, can you please upload it too? Thank you in advance!

**Comment by kevinjosethomas** [comment]
I haven't developed a commands.html yet, I will redo the template soon with a list of commands

**Comment by anselal** [comment]
please reopen this issue since it hasn't been resolved yet

**Comment by kevinjosethomas** [comment]
I will most likely not be adding a commands.html to this template, I will recreate the template with better design and more pages in the future.
